name: Update Discord Class Names
on:
    schedule:
        - cron: "0 0 * * *" # Daily check
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Class Name Updater
              uses: fedeericodl/discord-update-classnames@main
              with:
                  commit-message: "chore: update class names"
                  files: "src"
                  token: ${{ secrets.GITHUB_TOKEN }}
